name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t sneha-flask-app .

    - name: Tag & Push Docker image
      run: |
        docker tag sneha-flask-app ${{ secrets.DOCKER_USERNAME }}/sneha-flask-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/sneha-flask-app:latest
