name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t sneha-flask-app .

      - name: Tag & Push Docker image
        run: |
          docker tag sneha-flask-app ${{ secrets.DOCKERHUB_USERNAME }}/sneha-flask-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sneha-flask-app:latest
